<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <script>
    function Promise(executor) {
        var self = this
        self.status = 'pending' // Promise当前的状态
        self.data = undefined  // Promise的值

        // 这里暂时不清楚是干什么用的
        self.onResolvedCallback = [] // Promise resolve时的回调函数集，因为在Promise结束之前有可能有多个回调添加到它上面
        self.onRejectedCallback = [] // Promise reject时的回调函数集，因为在Promise结束之前有可能有多个回调添加到它上面
    
        // 定义 resolve 和 reject 
        function resolve(value) {
            if(self.status == 'pending'){
                self.status = 'resolved';
                self.data = value;
                for(var i = 0; i < self.onResolvedCallback.length; i++) {
                    self.onResolvedCallback[i](value)
                }
            }
        }

        function reject(reason) {
            if(self.status == 'pending'){
                self.status = 'rejected';
                self.data = reason;
                for(var i = 0; i < self.onRejectedCallback.length; i++) {
                    self.onRejectedCallback[i](reason)
                }
            }
        }

        try { // 考虑到执行executor的过程中有可能出错，所以我们用try/catch块给包起来，并且在出错后以catch到的值reject掉这个Promise
            executor(resolve, reject) // 执行executor
        } catch(e) {
            reject(e)
        }
    }


    Promise.prototype.then = function(onResolved, onRejected) {
        var self = this
        var promise2
    
        // 根据标准，如果then的参数不是function，则我们需要忽略它，此处以如下方式处理
        onResolved = typeof onResolved === 'function' ? onResolved : function(value) {return value}
        onRejected = typeof onRejected === 'function' ? onRejected : function(reason) {throw reason}
    
        if (self.status === 'resolved') {
            // 根据标准返回一个新promise对象
            return promise2 = new Promise(function(resolve, reject) {
                try {
                    let x = onResolved(self.data);
                    if(x instanceof Promise){
                        // 如果onResolved的返回值是一个Promise对象，直接取它的结果做为promise2的结果
                        x.then(resolve, reject) // 这里不太懂为什么是这样调用
                    }else{
                        // 给新promise对象 赋值
                        resolve(x)
                    }

                }catch(e) {
                    reject(e)
                }
                
            })
        }
    
        if (self.status === 'rejected') {
            return promise2 = new Promise(function(resolve, reject) {
            try {
                var x = onRejected(self.data)
                if (x instanceof Promise) {
                    x.then(resolve, reject)
                }else{
                    // 给新promise对象 赋值
                    reject(x)
                }
            } catch (e) {
                reject(e)
            }
            })
        }
    
        if (self.status === 'pending') {
            // 如果当前的Promise还处于pending状态，我们并不能确定调用onResolved还是onRejected，
            // 只能等到Promise的状态确定后，才能确实如何处理。
            // 所以我们需要把我们的**两种情况**的处理逻辑做为callback放入promise1(此处即this/self)的回调数组里
            // 逻辑本身跟第一个if块内的几乎一致，此处不做过多解释
            return promise2 = new Promise(function(resolve, reject) {
                self.onResolvedCallback.push(function(value) {
                    try {
                        var x = onResolved(self.data)
                        if (x instanceof Promise) {
                            x.then(resolve, reject)
                        }
                        
                    } catch (e) {
                        reject(e)
                    }
                })
        
                self.onRejectedCallback.push(function(reason) {
                    try {
                        var x = onRejected(self.data)
                        if (x instanceof Promise) {
                            x.then(resolve, reject)
                        }
                    } catch (e) {
                        reject(e)
                    }
                })
            })
        }
    }

    Promise.prototype.catch = function(onRejected) {
        return this.then(null, onRejected)
    }

    // var p1 = new Promise((resolve,reject) => {
    //     setTimeout(() => {
    //         console.log('resolve finish')
    //         resolve(1)
    //     },1000)
    // })

    // var p2 = p1.then(res => {
    //     return new Promise((resolve,reject) => {
    //         console.log('第二个')
    //         resolve(2)
    //     })
    // })
    // .then(res => {
    //     console.log('第三个',res)
    // })

    // console.log(p2);

    Promise.resolve(1).then(res => {
        console.log(res);
    })

    </script>
</body>
</html>

